### ISSUE TITLE
Compressed Stream?

### ISSUE THREAD

**Issue by soulslicer** [rrg-polito/mono-slam#2]
How would i be able to let this read from a compressed stream?

I tried using
rosrun mono-slam mono-slam conf/conf.cfg /image:=/frontcam/camera/image_color/compressed, but there was nothing/no output from the monoslam feed

**Comment by soulslicer** [comment]
It's seem fines when it works off a non-compressed stream

**Comment by zhijun123** [comment]
hello,
   I am trying to make this project work, but when I give a non-compressed stream, an error always occures.
[ERROR] [1555923916.482153801]: No Matching li

Do you know how to fix it? thank you.
