### ISSUE TITLE
RViz Error

### ISSUE THREAD

**Issue by soulslicer** [rrg-polito/mono-slam#3]
While the data seems to be publishing, I get this error inside RViz, when I try to visualize marker arrays:

For frame [/world]: Fixed Frame [map] does not exist

**Comment by ludusrusso** [comment]
Hey,
sorry for the late response, you can try to create a static transform between `/world` and `/map`, or force directly rviz to use the `/map` frame as main frame!

**Comment by soulslicer** [comment]
lmao
